### ISSUE TITLE
Only 8 channels on BeagleLogic system image

### ISSUE THREAD

**Issue by antoniomolram** [abhishek-kakkar/BeagleLogic#14]
Hi!
First, thanks for this beautiful project! I was making some captures and it is working perfect, but now I need the 12 channels (until 12 I do not need to modify the BBB, right?) but I don't know how to activate them. 

I saw in Internet that can be used with this driver option from Sigrok:
`sigrok-cli -d beaglelogic:numchannels=14 -c  samplerate=1M --time 1s --channels P8_27,P8_45,P8_44 -o output.sr`
but I am getting: 
`Unknown device option 'numchannels'.`

Ideas?
Thank you very much!

**Comment by abhishek-kakkar** [comment]
Use this instead:

`sigrok-cli -d beaglelogic:logic_channels=14 -c samplerate=1M --time 1s --channels P8_27,P8_45,P8_44 -o output.sr`

**Comment by antoniomolram** [comment]
Thank you! ;)
