### ISSUE TITLE
input voltage to the BBB

### ISSUE THREAD

**Issue by skypuppy** [abhishek-kakkar/BeagleLogic#16]
AIUI, none of the input pins on the BBB are allowed more than 1.8V.  How do sample most of the world?  Even most uprocessors output 3.3V, and then there is as much as 12v on full-blown RS-232.  How do we not let the smoke out of the BBB, especially when we're not sure of the voltage we're trying to sample???

**Comment by pro585code** [comment]
Test the voltage lvl first... Then use proper voltage divider to step down that voltage while trying to keep you signal intact?

**Comment by pro585code** [comment]
Your*

**Comment by ItsMeMegaMind** [comment]
Is there a way we can make an external ADC work with beaglelogic? That would solve the problem.

**Comment by abhishek-kakkar** [comment]
Google "PRUDAQ" for an external ADC interfacing with BeagleLogic.

I have designed a cape for the BeagleBone that allows safe interfacing of up to 5V logic level signals, and will work on enabling signal levels > 5V soon. Please watch the wiki page for announcements.

Closing this issue.
