### ISSUE TITLE
Pipe the data into python program

### ISSUE THREAD

**Issue by fwndz** [abhishek-kakkar/BeagleLogic#20]
hi
I am new in beaglelogic. I would like to ask how to pipe the sampling data into python code? Is it piping the data into python code will run in realtime? (i.e can the data  be piped directly to the python program or it should be saved in the file first before it can be pipe in the program? 

Thanks
Regards
fwndz

**Comment by TjebbeVQ** [comment]
Hello fwndz,

Did you by any chance find a solution to this question?
I'm having the same problem. 

Thanks
Tjebbe

**Comment by tchristle** [comment]
try:

f=open('/dev/beaglelogic','rb')
f.read(8)

**Comment by abhishek-kakkar** [comment]
Closing, please reopen if unresolved.
