### ISSUE TITLE
Update image to latest Debian Stretch and sigrok dependencies

### ISSUE THREAD

**Issue by buzmeg** [abhishek-kakkar/BeagleLogic#29]
As things stand, the current image for Debian cannot be apt-get update/upgrade because the dependency chains for sigrok go completely wonky.

**Comment by abhishek-kakkar** [comment]
There is already a Stretch version of the BeagleLogic released 7 months ago. You can download it from http://beaglelogic.readthedocs.io/en/latest/beaglelogic_system_image.html
