### ISSUE TITLE
error in beaglelogic_map_and_submit_all_buffers()

### ISSUE THREAD

**Issue by mixaz** [abhishek-kakkar/BeagleLogic#34]
https://github.com/abhishek-kakkar/BeagleLogic/blob/master/kernel/beaglelogic.c#L343 - 'j' should be used instead of 'i'

**Comment by abhishek-kakkar** [comment]
Thanks for noticing. Will be fixed in the next release, which will happen
soon.

**Comment by abhishek-kakkar** [comment]
This has been fixed in source, will push out a commit shortly that will fix the bug. Thanks again for pointing it out!
