### ISSUE TITLE
A question about prudaq-ch0.asm driver

### ISSUE THREAD

**Issue by arashebadi** [abhishek-kakkar/BeagleLogic#35]
Dear Abhishek-kakkar,

Thanks a lot for you assume work! I am trying to modify the driver for a single channel ADC with 40Msps to 50Msps and 8 bits. I managed to remove one of the NOPs and speed up the script a little bit. But I am still not fast, I appreciate if you can give me more details about these two lines and the possibility of moving them somewhere else in the code. What do you mean by Jab?
 
XOUT   10, &R21, 36                                   ; Move data across the broadside
LDI    R31, PRU1_PRU0_INTERRUPT + 16    ; Jab PRU0

https://github.com/abhishek-kakkar/BeagleLogic/blob/3cea157d312a685547a2ca9aa66cefacd1fd2cee/firmware/custom/prudaq/prudaq-ch0.asm#L188

Moreover, is there any way to stop the sampling process in Debian after running your driver?

Best Regards,
Arasg

**Comment by abhishek-kakkar** [comment]
Closing issue as there has been no further correspondence. Please reopen if necessary.
