### ISSUE TITLE
Does this require the BeagleLogic Cape?

### ISSUE THREAD

**Issue by MicroTransactionsMatterToo** [abhishek-kakkar/BeagleLogic#37]
Just getting started with playing around with FPGA's, and as such, I need an oscilloscope of some sort. The BeagleLogic seemed a good option, as I already have a BeagleBone Black. However, I'm unsure of whether it requires the BeagleLogic Cape, and if it doesn't, which pins would I be using to sample data with.

Many Thanks,
Ennis Massey

**Comment by abhishek-kakkar** [comment]
Hi, apologies for late reply. You don't need a cape to get started with BeagleLogic as long as you are working with 3.3V signals, you just have to connect them to the PRU pins (look at beagleboard.org/bone101) - look at PRU1 pins from 0 to 11 - P8_45 - Channel 0, P8_46 - Channel 1 and so on.
