### ISSUE TITLE
kicad lib paths

### ISSUE THREAD

**Issue by macsimski** [abhishek-kakkar/BeagleLogic#6]
hello again.

i've looked at your itinial commit on the cape and there seems to be a problem with the libs, I am unable to find bbb.lib

**Comment by abhishek-kakkar** [comment]
Due to settings in the .gitignore, these files weren't included in the commit. Thanks for pointing out!
Fixed now.

4ebee261267fb130bacc76e08960fa0cf48e93bc and e6bd342680c797809f9702191431913fa466c1c9 close #6

**Comment by macsimski** [comment]
cool! may i make some suggestions concerning the cape? maybe offlist though

On 22-01-15 15:06, Kumar Abhishek wrote:
> Due to settings in the .gitignore, these files weren't included in the
> commit. Thanks for pointing out!
> Fixed now.
>
> 4ebee26
> <https://github.com/abhishek-kakkar/BeagleLogic/commit/4ebee261267fb130bacc76e08960fa0cf48e93bc>
> and e6bd342
> <https://github.com/abhishek-kakkar/BeagleLogic/commit/e6bd342680c797809f9702191431913fa466c1c9>
> close #6 <https://github.com/abhishek-kakkar/BeagleLogic/issues/6>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abhishek-kakkar/BeagleLogic/issues/6#issuecomment-71024468>.
>

-- 
Met vriendelijke Groet,

Simon Claessen
drukknop.nl

**Comment by abhishek-kakkar** [comment]
Sure, you have my email address the commit messages
